clc;
clear('all');
% rng('default');
warning('off','all');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% SIMULATION CONFIGURATION %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
PARAMETERS = {};
PARAMETERS.SIMULATION = {};
PARAMETERS.CONTROL = {};
PARAMETERS.DISTURBANCE = {};
PARAMETERS.PLOT = {};
PARAMETERS.PLANT = {};
PARAMETERS.REFERENCE = {};

PARAMETERS.PLANT.X_1_MAX = pi/4;
PARAMETERS.PLANT.X_2_MAX = 2.0*pi;
PARAMETERS.CONTROL.SCALE_FACTOR = 0.5;
PARAMETERS.CONTROL.ERROR_PRECISION = 0.05; 
PARAMETERS.SIMULATION.TOTAL_TIME = 8;
PARAMETERS.PLOT.CREATE_PDF = 0;
PARAMETERS.PLOT.FONT_SIZE = 14;
PARAMETERS.DISTURBANCE.FREQUENCY_MAX = 10;
PARAMETERS.SIMULATION.SETTLING_TIME = 1.0;
PARAMETERS.PLANT.GRAVITY = 9.8;
PARAMETERS.PLANT.CART_MASS = 1;
PARAMETERS.PLANT.POLE_MASS = 0.1;
PARAMETERS.PLANT.POLE_HALF_LENGTH = 0.5;
PARAMETERS.PLANT.INITIAL_STATE = [0.0 0.0]'; % histograma !!
%     PARAMETERS.PLANT.INITIAL_STATE = [0.9 0.5*pi]'; 
%     PARAMETERS.PLANT.INITIAL_STATE = [0.5*pi/2.0 2*pi]';
